# Generated by Django 4.2.6 on 2023-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_location_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
