# Generated by Django 4.2.6 on 2023-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
